# Generated by Django 2.2.4 on 2020-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClicksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('operating_system', models.CharField(max_length=10)),
                ('impressions', models.CharField(max_length=50)),
                ('clicks', models.CharField(max_length=50)),
                ('installs', models.CharField(max_length=50)),
                ('spend', models.CharField(max_length=50)),
                ('revenue', models.CharField(max_length=50)),
            ],
        ),
    ]
