# Generated by Django 2.2.4 on 2020-02-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clicksinfo',
            old_name='operating_system',
            new_name='os',
        ),
    ]
