# Generated by Django 2.2.4 on 2020-02-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_auto_20200210_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicksinfo',
            name='cpi',
            field=models.CharField(default='0000000000', max_length=50),
        ),
    ]
