# Generated by Django 2.2.4 on 2020-02-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_auto_20200210_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicksinfo',
            name='cpi',
        ),
        migrations.AlterField(
            model_name='clicksinfo',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
